Add 42 School provider
pilcrowonpaper/arctic pull request #109
Opened 2024-04-23 15:57 UTC by awbx

ref to #108

2024-04-24 03:32 UTC, pilcrowonpaper commented on src/providers/42.ts
> +export type Scope =
Can you remove this to be consistent with other providers?

2024-04-24 03:36 UTC, pilcrowOnPaper requested changes

2024-04-24 03:36 UTC, pilcrowOnPaper commented on src/providers/42.ts
> +	scope?: string;
I don't think `scope` required here

2024-04-24 03:36 UTC, pilcrowonpaper commented on src/providers/42.ts
> +	refreshToken?: string | null;
Can you replace `a?: A` with `a: A | null`?

2024-04-24 03:36 UTC, pilcrowOnPaper commented on src/providers/42.ts
> +		const authorizeEndpoint = baseUrl + "/oauth/authorize";
Super minor nit-pick but can you just do

```suggestion
		const authorizeEndpoint = "https://api.intra.42.fr/oauth/authorize";
```

and make it a global variable (see providers like Apple)

2024-04-24 03:36 UTC, pilcrowOnPaper commented on src/providers/42.ts
> +			redirectURI?: string;
Is `redirectURI` required or not (the docs you wrote seems to indicate that it is)?

2024-04-24 10:17 UTC, awbx commented
include the modifications as suggested by @pilcrowOnPaper earlier.

2024-04-24 10:17 UTC, awbx commented
ready to merge

2024-04-24 10:20 UTC, awbx commented on src/providers/42.ts
> +	refreshToken?: string | null;
i can't because it's not compatible with the `validateAuthorizationCode` result type.

2024-04-24 14:14 UTC, pilcrowonpaper commented on src/providers/42.ts
> +	refreshToken?: string | null;
I'm not sure what you mean?

```ts
const tokens: FortyTwoTokens = {
			accessToken: result.access_token,
			refreshToken: result.refresh_token ?? null, 
			expiresIn: result.expires_in ?? null,
}
```

2024-04-26 11:02 UTC, awbx commented on src/providers/42.ts
> +	refreshToken?: string | null;
my apologies, I've made the change as you suggested

2024-04-26 11:02 UTC, awbx commented
ready to merge

2024-04-26 12:36 UTC, pilcrowOnPaper commented on src/providers/42.ts
> +	refreshToken: string | null;
Is `refresh_token` and `expires_in` even included in the response?

2024-04-26 12:38 UTC, pilcrowOnPaper commented on src/providers/42.ts
> +	refreshToken: string | null;
Looks like `refresh_token` isn't included so you can just omit that, while `expires_in` is - so please replace it with `accessTokenExpiresAt` field (see other providers)

2024-04-26 13:11 UTC, awbx commented on src/providers/42.ts
> +	refreshToken: string | null;
done

2024-04-26 14:50 UTC, pilcrowOnPaper commented on src/providers/42.ts
> +	create_at: number;
Final fix - should be `created_at`!

2024-04-26 14:50 UTC, pilcrowOnPaper commented on src/providers/42.ts
> +	create_at: number;
```suggestion
	created_at: number;
```

2024-04-26 14:51 UTC, pilcrowOnPaper approved these changes

2024-04-26 14:51 UTC, pilcrowOnPaper approved these changes

2024-04-26 14:51 UTC, merged

2024-04-26 14:51 UTC, pilcrowOnPaper commented
Thanks!