Lichess provider
pilcrowonpaper/arctic pull request #45
Opened 2024-01-22 00:41 UTC by sukalov

I've needed auth via Lichess, and decided to try implementing custom provider with lucia v3(beta). It worked out really well, and I'd love to share the provider code with the community. If you find it interesting enough, I'll add according documentation later this week

2024-01-22 01:24 UTC, pilcrowOnPaper requested changes

2024-01-22 01:24 UTC, pilcrowOnPaper commented on src/providers/lichess.ts
> +			redirectURI: string;
If the redirect URI is required

```ts
constructor(clientId: string, clientSecret: string, redirectURI: string) {}
```

If not,

```ts
constructor(clientId: string, clientSecret: string, options?: {
  redirectURI?: string
}) {}
```

2024-01-22 01:24 UTC, pilcrowOnPaper commented on src/providers/lichess.ts
> +			scope: string[];
I think this is a mistake?
```suggestion
```

2024-01-22 01:24 UTC, pilcrowOnPaper commented on src/providers/lichess.ts
> +			scope: string[];
```suggestion
			scopes?: string[];
```

2024-01-22 01:24 UTC, pilcrowOnPaper commented on src/providers/lichess.ts
> +		clientSecret: string,
Does Lichess require a client secret?
https://lichess.org/api#tag/OAuth/operation/apiToken

2024-01-22 01:24 UTC, pilcrowOnPaper commented on src/providers/lichess.ts
> +		const options: ValidateAuthorizationCodeRequestOptions = {
You can just pass the options to `this.client.validateAuthorizationCode()` directly to be consistent with the other providers (and remove `ValidateAuthorizationCodeRequestOptions`)

2024-01-22 03:43 UTC, pilcrowOnPaper requested changes
Can you also format it by running `pnpm format`?

2024-01-22 03:43 UTC, pilcrowOnPaper commented on src/providers/lichess.ts
> +		options?: {
This can be removed since `scopes` isn't required

2024-01-22 10:13 UTC, pilcrowOnPaper approved these changes
Can you update the docs and the README?

2024-01-22 10:14 UTC, sukalov commented
sure! i will

2024-01-24 16:38 UTC, sukalov commented
HI @pilcrowOnPaper  
I've made models of Lichess api responses but couldn't find, if I can provide those somewhere in the codebase.. Is there a place for such type specifications?

2024-01-24 23:36 UTC, pilcrowOnPaper commented
Can you update `sidebar` in `docs/malta.config.json`?

2024-01-24 23:43 UTC, pilcrowOnPaper commented
We don't export the user type anymore btw

2024-01-24 23:43 UTC, pilcrowOnPaper approved these changes

2024-01-24 23:43 UTC, merged

2024-01-24 23:44 UTC, pilcrowOnPaper commented
Thanks!

2024-01-24 23:45 UTC, sukalov commented
> We don't export the user type anymore btw

yep, i've noticed it's fine
thank you! appreciate your work