Add Intuit provider
pilcrowonpaper/arctic pull request #97
Opened 2024-04-01 16:20 UTC by epotter2297

This PR adds [Intuit OAuth](https://developer.intuit.com/app/developer/qbo/docs/develop/authentication-and-authorization/oauth-2.0) provider ([#96](https://github.com/pilcrowOnPaper/arctic/issues/96))

2024-04-02 23:05 UTC, pilcrowOnPaper requested changes
Can you also update the providers list in the README?

2024-04-02 23:05 UTC, pilcrowOnPaper commented on src/providers/intuit.ts
> +			authenticateWith: "request_body",
The credentials should be send within the authorization header, so this should be `http_basic_auth`. That's the default in Oslo, you can just remove this line.

https://developer.intuit.com/app/developer/qbo/docs/develop/authentication-and-authorization/oauth-2.0#exchange-code-for-tokens

2024-04-02 23:05 UTC, pilcrowOnPaper commented on src/providers/intuit.ts
> +			authenticateWith: "request_body",
ditto

2024-04-03 12:38 UTC, epotter2297 commented
Those updates should all be done now :)

2024-04-03 13:27 UTC, pilcrowOnPaper approved these changes

2024-04-03 13:27 UTC, merged

2024-04-03 13:27 UTC, pilcrowOnPaper commented
Thanks!